### ISSUE TITLE
Creating contribution guidelines

### ISSUE THREAD

**Issue by devinhalladay** [GD399-OSD/GD399-Meta#1]
This issue is copied from a similar issue in the [GD399-resources-readings](https://github.com/GD399-OSD/GD399-resources-readings) repo.

From @bjornmeansbear: "Advise on how best to fork, add, then pull request. As well as how to briefly explain what you are adding/changing to make it more useful and meaningful."

**Comment by devinhalladay** [comment]
Here's a good resource for how to write good contribution guidelines, but they seem to be catered mostly to software projects: https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by devinhalladay** [comment]
RIP GD399-OSD 💔 @bjornmeansbear

**Comment by bjornmeansbear** [comment]
Maybe one day I can run this course again!
@devinhalladay how goes it!? I've been working on some presentations and workshops about this stuff to try and shop around to other GD departments – we should catch up one of these days!
