### ISSUE TITLE
Potential Project Idea: Our own etherpad?

### ISSUE THREAD

**Issue by bjornmeansbear** [GD399-OSD/GD399-Meta#3]
codebase: https://github.com/ether/etherpad-lite

totally allowed to roll your own.

**Comment by devinhalladay** [comment]
This would be a really fun project! I'd be down to help out if others want to hack on it. 

Maybe a good start would be to figure out if/how we can host this as a service (i.e. on Heroku or some other free thing). I also have a server running Ubuntu that we can potentially use for this & other projects. I found [this fork](https://github.com/bright-star/etherpad-lite-heroku) of etherpad-lite that can deploy right to Heroku but it's way out of sync with the etherpad repo

**Comment by bjornmeansbear** [comment]
I'm also happy to roll a new digital ocean drop or run it on one of my servers as well. I can rope a developer pal or two into collaborating as well that way?

**Comment by millenniallglyphs** [comment]
Etherpad seems like a useful tool. I voice my support for this project.

**Comment by devinhalladay** [comment]
I've forked `etherpad-lite-heroku` over at https://github.com/GD399-OSD/osd-etherpad.git so we can begin hacking on and using this. The etherpad instance is being hosted on Heroku at https://gd399-ether.herokuapp.com.

Closing this issue; if anyone wants to contribute, please continue the discussion on the new repo!
