### ISSUE TITLE
Anyone interested in contributing to one of my OSS projects?

### ISSUE THREAD

**Issue by devinhalladay** [GD399-OSD/GD399-Meta#4]
This is sort of a personal plug, but I did this thing a while ago — https://github.com/devinhalladay/spotio — that got a ton of users until I ran out of steam to maintain the project. If anyone's interested in helping out in any capacity, let me know! Would be cool to revive this and I have some ideas for what the project roadmap might look like.

**Comment by KHurleyDesign** [comment]
I see in the issues that there is not a windows version of it but that you were planning on potentially working on one, is that something you ever got around to?

**Comment by devinhalladay** [comment]
@KHurleyDesign nope I never got around to it, but you're welcome to look into it and submit a PR! Someone needs to update all the CSS and the Grunt buildpack to work with the new versions of Spotify first, though. The whole app is broken in its current state.
