### ISSUE TITLE
Let's use our hands! I propose we meet in a space with tools

### ISSUE THREAD

**Issue by millenniallglyphs** [GD399-OSD/GD399-Meta#9]
After reading about autoprogettazione, I want to explore design with my hands. I've been thinking that much of the design I want to explore involves interventions in space. For this I need to be around tools. Furthermore, the action of carving, tooling, cutting, etc, seem to be the most open tools available. What does a poster look like if I make it in the wood shop rather than on the computer?

**Comment by bjornmeansbear** [comment]
Wonderful question. We could also just bring paper and pencils and rulers and rub down type, etc. and physically draw out renderings of posters, etc. as well? Try to channel pre-computer graphic design?

**Comment by millenniallglyphs** [comment]
Yes! That's a great start point. What's more it's easy!

**Comment by mazzybell** [comment]
@millenniallglyphs /whomever else wants to do this.... want to work on a collaborative print???? maybe a reductive screen print or a monotype?

**Comment by millenniallglyphs** [comment]
@mazzybell sounds cool! I'm down to make something!
